#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: MediSafe → LINE + Cloud Run setup
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "MediSafe: LINE Developers + Cloud Run setup"

# ── Stage 1: gcloud sanity check + project selection ──────────────────────
stage "Google Cloud: CLI + project"
say "This deploys the FastAPI backend (with its existing Dockerfile) to Cloud Run."
if ! command -v gcloud >/dev/null 2>&1; then
  warn "gcloud CLI not found on PATH."
  note "Install it from https://cloud.google.com/sdk/docs/install, then re-run this script."
  SKIPPED+=("Install gcloud CLI, then re-run this wizard from Stage 1")
  finish
  exit 1
fi
step "Make sure you're logged in (a browser tab will open if not)."
gcloud auth login --brief --update-adc || true
ask GCP_PROJECT_ID "GCP project ID to deploy into (e.g. medisafe-line-123):"
gcloud config set project "$GCP_PROJECT_ID" >/dev/null
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
ask GCP_REGION "Cloud Run region (e.g. asia-east1 for Taiwan):"
write_env GCP_REGION "$GCP_REGION"

# ── Stage 2: enable required APIs ──────────────────────────────────────────
stage "Google Cloud: enable APIs"
say "Enabling Cloud Run, Cloud Build, and Artifact Registry for this project."
gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com \
  --project "$GCP_PROJECT_ID"
note "APIs enabled (this can take ~30s to fully propagate the first time)."
pause

# ── Stage 3: LINE provider + Messaging API channel ─────────────────────────
stage "LINE Developers: create Messaging API channel"
say "You'll create (or reuse) a Provider, then a Messaging API channel under it."
open_url "https://developers.line.biz/console/"
step "Click 'Create a new provider' (or pick an existing one) and name it, e.g. MediSafe."
step "Inside the provider, click 'Create a new channel' → choose 'Messaging API'."
step "Fill in the channel name/description/category (any values are fine for the demo), agree to terms, create it."
pause "Channel created?"
step "Open the new channel → 'Messaging API' tab → scroll to 'Channel secret' → copy it."
ask_secret LINE_CHANNEL_SECRET "Paste the Channel secret:"
step "On the same tab, under 'Channel access token', click 'Issue' (long-lived token) and copy it."
ask_secret LINE_CHANNEL_ACCESS_TOKEN "Paste the Channel access token:"
write_env LINE_CHANNEL_SECRET "$LINE_CHANNEL_SECRET"
write_env LINE_CHANNEL_ACCESS_TOKEN "$LINE_CHANNEL_ACCESS_TOKEN"
note "Leave this tab open — we'll come back to set the webhook URL after deploying."

# ── Stage 4: first Cloud Run deploy (webhook not wired up yet) ─────────────
stage "Cloud Run: first deploy"
say "Deploying now so we have a stable HTTPS URL to give LINE. GEMINI_API_KEY is read from your local .env."
GEMINI_API_KEY_CURRENT=$(_existing GEMINI_API_KEY || true)
if [[ -z "$GEMINI_API_KEY_CURRENT" ]]; then
  ask_secret GEMINI_API_KEY "Paste your GEMINI_API_KEY (not found in .env):"
  write_env GEMINI_API_KEY "$GEMINI_API_KEY"
else
  GEMINI_API_KEY="$GEMINI_API_KEY_CURRENT"
  note "Using existing GEMINI_API_KEY from .env."
fi
SERVICE_NAME="medisafe-line"
write_env SERVICE_NAME "$SERVICE_NAME"
say "Building and deploying from source (uses the repo's Dockerfile) — this can take a few minutes."
gcloud run deploy "$SERVICE_NAME" \
  --source . \
  --project "$GCP_PROJECT_ID" \
  --region "$GCP_REGION" \
  --allow-unauthenticated \
  --set-env-vars "GEMINI_API_KEY=${GEMINI_API_KEY},LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN},LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET},LIFF_REPORT_URL=https://example.com/placeholder"
CLOUD_RUN_URL=$(gcloud run services describe "$SERVICE_NAME" \
  --project "$GCP_PROJECT_ID" --region "$GCP_REGION" --format='value(status.url)')
write_env CLOUD_RUN_URL "$CLOUD_RUN_URL"
note "Deployed at: $CLOUD_RUN_URL"
note "--allow-unauthenticated is required so LINE's servers can reach /line/webhook and Cloud Scheduler can reach /line/send-reminders."
pause

# ── Stage 5: wire the webhook URL into the LINE channel ────────────────────
stage "LINE Developers: set webhook URL"
say "Back in the LINE Developers console (same channel, 'Messaging API' tab):"
step "Set 'Webhook URL' to: ${CLOUD_RUN_URL}/line/webhook"
step "Click 'Verify' — it should return success now that Cloud Run is live."
step "Toggle 'Use webhook' to Enabled."
step "Scroll to 'LINE Official Account features' → turn OFF 'Auto-reply messages' and 'Greeting messages' (so only our webhook responds)."
confirm "Webhook verified and enabled?" || warn "Remember to finish this before testing in LINE."

# ── Stage 6: create the LIFF app ────────────────────────────────────────────
stage "LINE Developers: create LIFF app"
say "The LIFF app serves liff_report.html — the safety report page opened from the Flex Message button."
step "In the same channel, go to the 'LIFF' tab → 'Add'."
step "LIFF app name: e.g. MediSafe Report."
step "Size: Full."
step "Endpoint URL: ${CLOUD_RUN_URL}/liff_report.html"
step "Scope: profile (needed for liff.getProfile() to get the userId)."
step "Save, then copy the generated LIFF ID (format: 1234567890-AbCdEfGh)."
ask LIFF_ID "Paste the LIFF ID:"
write_env LIFF_ID "$LIFF_ID"
LIFF_REPORT_URL="https://liff.line.me/${LIFF_ID}"
write_env LIFF_REPORT_URL "$LIFF_REPORT_URL"

# ── Stage 7: bake the LIFF ID into the page and redeploy ───────────────────
stage "Redeploy with the real LIFF ID"
say "Updating frontend/liff_report.html's LIFF_ID constant, then rebuilding so the Flex Message button and LIFF page both work end-to-end."
LIFF_HTML="frontend/liff_report.html"
if [[ -f "$LIFF_HTML" ]]; then
  sed -i.bak "s|const LIFF_ID = \".*\";|const LIFF_ID = \"${LIFF_ID}\";|" "$LIFF_HTML"
  rm -f "${LIFF_HTML}.bak"
  note "Updated LIFF_ID in $LIFF_HTML."
else
  warn "$LIFF_HTML not found — set LIFF_ID in it manually before redeploying."
fi
say "Redeploying to Cloud Run with the real LIFF_REPORT_URL and the updated page..."
gcloud run deploy "$SERVICE_NAME" \
  --source . \
  --project "$GCP_PROJECT_ID" \
  --region "$GCP_REGION" \
  --allow-unauthenticated \
  --set-env-vars "GEMINI_API_KEY=${GEMINI_API_KEY},LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN},LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET},LIFF_REPORT_URL=${LIFF_REPORT_URL}"
note "Redeployed. Scan the channel's QR code (Messaging API tab) with LINE and send a medicine photo to test."

# ── Stage 8: optional Cloud Scheduler for reminders ─────────────────────────
stage "Optional: Cloud Scheduler for reminders"
if confirm "Set up a recurring job to POST ${CLOUD_RUN_URL}/line/send-reminders ?"; then
  gcloud services enable cloudscheduler.googleapis.com --project "$GCP_PROJECT_ID"
  ask REMINDER_CRON "Cron schedule in region time, e.g. '0 8 * * *' for daily 8am:"
  gcloud scheduler jobs create http medisafe-reminders \
    --project "$GCP_PROJECT_ID" \
    --location "$GCP_REGION" \
    --schedule "$REMINDER_CRON" \
    --uri "${CLOUD_RUN_URL}/line/send-reminders" \
    --http-method POST \
    || note "Job may already exist — edit it in the Cloud Scheduler console if this failed."
  note "Reminder job created. Note: /line/send-reminders currently pushes to every registered user on every trigger — it doesn't yet filter by the reminder's registered time-of-day."
else
  note "Skipped. You can add this later from the Cloud Scheduler console or by re-running this stage."
fi

finish
note "Summary:"
note "  Cloud Run URL:  ${CLOUD_RUN_URL:-<not set>}"
note "  Webhook URL:    ${CLOUD_RUN_URL:-<not set>}/line/webhook"
note "  LIFF endpoint:  ${CLOUD_RUN_URL:-<not set>}/liff_report.html"
note "  LIFF ID:        ${LIFF_ID:-<not set>}"
